import {
  Welcome,
  Demographic,
  FirstQuestion,
  SecondQuestion,
  ThirdQuestion,
  FourthQuestion,
  MissingMessageQuestion,
  InferredQuoteQuestion,
  FifthQuestion,
  SixthQuestion,
  SeventhQuestion,
  EighthQuestion,
  FirstExplanation,
  SecondExplanation,
  ThirdExplanation,
  FirstChat,
  FirstChatFeedback,
  SecondChat,
  SecondChatFeedback,
  ThirdChat,
  ThirdChatFeedback,
  FourthChat,
  FourthChatFeedback,
  Feedback,
  ThankYou,
} from '../screens';

const navigationalMap = [
  { path: '/', screen: Welcome },
  { path: '/demographic', screen: Demographic },
  { path: '/explanations/1', screen: FirstExplanation },
  { path: '/questions/1', screen: FirstQuestion },
  { path: '/questions/2', screen: SecondQuestion },
  { path: '/questions/3', screen: ThirdQuestion },
  { path: '/questions/4', screen: FourthQuestion },
  { path: '/questions/5', screen: FifthQuestion },
  { path: '/questions/6', screen: SixthQuestion },
  { path: '/questions/7', screen: SeventhQuestion },
  { path: '/questions/8', screen: EighthQuestion },
  { path: '/explanations/2', screen: SecondExplanation },
  { path: '/explanations/3', screen: ThirdExplanation },
  { path: '/chats/1', screen: FirstChat },
  { path: '/feedback/1', screen: FirstChatFeedback },
  { path: '/chats/2', screen: SecondChat },
  { path: '/feedback/2', screen: SecondChatFeedback },
  { path: '/questions/missing-message', screen: MissingMessageQuestion },
  { path: '/questions/inferred-quote', screen: InferredQuoteQuestion },
  { path: '/chats/3', screen: ThirdChat },
  { path: '/feedback/3', screen: ThirdChatFeedback },
  { path: '/chats/4', screen: FourthChat },
  { path: '/feedback/4', screen: FourthChatFeedback },
  { path: '/feedback', screen: Feedback },
  { path: '/thank-you', screen: ThankYou },
];

export default navigationalMap;
