import {
  Welcome,
  Demographic,
  FirstQuestion,
  SecondQuestion,
  Definition,
  Expectation,
  Usage,
  UsageStatistics,
  Explanation,
  FurtherExplanation,
  FirstExplanation,
  FirstChat,
  FirstChatFeedback,
  SecondChat,
  SecondChatFeedback,
  ThirdChat,
  ThirdChatFeedback,
  FourthChat,
  FourthChatFeedback,
  FifthChat,
  FifthChatFeedback,
  Feedback,
  ThankYou,
} from '../screens';

const navigationalMap = [
  { path: '/', screen: Welcome },
  { path: '/demographic', screen: Demographic },
  { path: '/explanation/1', screen: FirstExplanation },
  { path: '/questions/1', screen: FirstQuestion },
  { path: '/questions/2', screen: SecondQuestion },
  { path: '/definition', screen: Definition },
  { path: '/expectation', screen: Expectation },
  { path: '/usage', screen: Usage },
  { path: '/usage-statistics', screen: UsageStatistics },
  { path: '/explanation', screen: Explanation },
  { path: '/further-explanation', screen: FurtherExplanation },
  { path: '/chats/1', screen: FirstChat },
  { path: '/feedback/1', screen: FirstChatFeedback },
  { path: '/chats/2', screen: SecondChat },
  { path: '/feedback/2', screen: SecondChatFeedback },
  { path: '/chats/3', screen: ThirdChat },
  { path: '/feedback/3', screen: ThirdChatFeedback },
  { path: '/chats/4', screen: FourthChat },
  { path: '/feedback/4', screen: FourthChatFeedback },
  { path: '/chats/5', screen: FifthChat },
  { path: '/feedback/5', screen: FifthChatFeedback },
  { path: '/feedback', screen: Feedback },
  { path: '/thank-you', screen: ThankYou },
];

export default navigationalMap;
